spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trade_db?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081